CREATE TABLE `player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `mail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PLAYER_USERNAME_UNIQUE` (`username` ASC),
  UNIQUE INDEX `PLAYER_MAIL_UNIQUE` (`mail` ASC));
